#!/bin/bash
echo "$(echo -ne "\002")$(echo -ne "\003")4You have been visited by the doge bird of shibe. good luck and prosperity will come to you, but only if you post \"thanks doge\" in this channel."

