#!/bin/bash
# sys.sh - prints 
#temp=  sensors | grep temp1 | sed 's/(crit = +[0-9][0-9]\.[0-9]°C)//' | sed 's/temp1:\s\+ +//g'
#uptime= uptime
#version= grep VERSION ../config | sed 's/[VERSION="]//g'

case $1 in
	temp)		out= sensors | grep temp1 | sed 's/(crit = +[0-9][0-9]\.[0-9]°C)//' | sed 's/temp1:\s\+ +//g';;
	uptime)		out= uptime;;
	version)	out= grep VERSION ../config | sed 's/[VERSION="]//g';;
	-h)		out= "temp, uptime, version";;
	#*) 		out= "";;
esac
echo ${out}


