#!/bin/bash
# sys.sh - prints 
#temp=  sensors | grep temp1 | sed 's/(crit = +[0-9][0-9]\.[0-9]°C)//' | sed 's/temp1:\s\+ +//g'
#uptime= uptime
#version= grep VERSION ../config | sed 's/[VERSION="]//g'

if [ ${2} = "temp" ]; then
    out= sensors | grep temp1 | sed 's/(crit = +[0-9][0-9]\.[0-9]°C)//' | sed 's/temp1:\s\+ +//g'
elif [ ${2} = "uptime" ]; then
    out=$(uptime +nc)
elif [ ${2} = "version" ]; then
    out= grep VERSION ./config | sed 's/[VERSION="]//g'
else
    out="invalid argument, commands: temp, uptime, version"
fi

echo ${out}


