#!/usr/bin/env bash

run=true

helpp() {
    echo " "
    echo "» SADBOT -configuration for networks + channels found in sadbot/config"
    echo "» modues found in sadbot/modules - called by filename, output in to channel whatever the file prints"
}

verbose=false
hlp=false
case $@ in
	-v) verbose=true;;
	--verbose) verbose=true;;
	-h) hlp=true;;
	--help) hlp=true;;
esac

init() {
    ghost=true
    if $hlp ; then 
        helpp
    fi
    source ./config
    source ./irc
    echo " "
    echo "» Sadbot - Spectrum Andri Droid BOT"
    echo "» Jonnecting to $NETWORK with nick \`$NICK\`"
    for chan in ${CHANNEL[@]}; do
	    echo "» Joining $chan"
    done
}

conn() {
    exec 3<>/dev/tcp/${NETWORK}/${PORT}; #connects to irc network
    echo "USER ${IDENT} 0 1 :$IRCNAME " >&3;
    echo "NICK ${NICK}" >&3;
}

parse() {
    IFS=$'\r\n' MODULES=($(for file in ./modules/*; do echo ${file##*/}; done))
    for mod in ${MODULES[@]}; do 
        if [[ $msg_in =~ "::$mod" ]]; then
            delim="::$mod"
            arg=$(echo $msg_in | awk -F $delim '{print $NF}')
            get_chan $msg_in
	        handle
        fi
    done
}

handle() {
    output=$(./modules/$mod $arg)
    if [[ $output =~ ">>ACT<<" ]]; then
        strip=$(echo $output | awk -F '<<' '{print $NF}')
        msg_act $nickchan $strip
    elif [[ $output =~ ">>MSG<<" ]]; then
        strip=$(echo $output | awk -F '<<' '{print $NF}')
        msg_out $nickchan $strip
    elif [[ $output =~ ">>RBC<<" ]]; then
        strip=$(echo $output | awk -F '<<' '{print $NF}')
        msg_rbc $nickchan $strip
    else 
        msg_out $nickchan $(./modules/$mod $arg) 
    fi
}

main() {
    while [ true ]; do
	read msg_in <&3;
        if $verbose ; then
	    echo $msg_in
	fi
    parse
    ping
    ghost 		#will ghost but doesn't join channels
    if $run ; then	#really hacky please fix me
	    if $ghost ; then
	        join
	        echo "» Joining Channels"
	        ident
        fi
        run=false
    fi
    done
}

init && conn && main;
