#!/bin/bash
if [[ $3 =~ 'http://'*'.'* ]] ; then
    #gets the amount of hits from the database
    source ./data/uri_hits_db
    #parses the url input from the channel
    base=$(echo "$3" | awk -F 'http://' '{print $2}' | awk -F ' ' '{print $1}')
    url="http://$base"
    filename=$(echo $base | awk -F '/' '{print $2}')
    #should check if the url is a link to an image
    if [[ $url =~ '.png' || $url =~ '.jpg' || $url =~ '.jpeg' || $url =~ '.gif' || $url =~ '.svg' || $url =~ '.tiff' ]] ; then
        echo "[ URL number ${HITS} by ${1} ] - [ file = $filename | $(ruby ./ruby/getsize.rb $url)"
    else
        uri_parse=$(wget -O- $url -q -nv | grep '<title>' | awk -F '<title>' '{print $NF}' | awk -F '</title>' '{print $1}')
        #outputs the final result with the user's name, and the amount of hits
        echo "[ URL number ${HITS} by ${1} ] - $uri_parse"
        #increments the hit counter
    fi
        HITSNEW=$(($HITS + 1))
        echo 'HITS='$HITSNEW > ./data/uri_hits_db
elif [[ $3 =~ 'https://'*'.'* ]] ; then
    source ./data/uri_hits_db
    base=$(echo "$3" | awk -F 'https://' '{print $2}' | awk -F ' ' '{print $1}')
    url="https://$base"
    filename=$(echo $base | awk -F '/' '{print $2}')
    if [[ $url =~ '.png' || $url =~ '.jpg' || $url =~ '.jpeg' || $url =~ '.gif' || $url =~ '.svg' || $url =~ '.tiff' ]] ; then
        echo "[ URL number ${HITS} by ${1} ] - [ file = $filename | $(ruby ./ruby/getsize.rb $url)"
    else
        uri_parse=$(wget -O- $url -q -nv | grep '<title>' | awk -F '<title>' '{print $NF}' | awk -F '</title>' '{print $1}')
        echo "[ URL number ${HITS} by ${1} ] - $uri_parse"
    fi
    HITSNEW=$(($HITS + 1))
    echo 'HITS='$HITSNEW > ./data/uri_hits_db
fi
