#!/usr/bin/env python
#we only need randint for this script
from random import randint
#picks a random number to be used in the color
ranColor= randint(1,16)
#outputs the random color
print("x\003" + str(ranColor) + "You have been visited by the doge bird of shibe. good luck and prosperity will come to you, but only if you post \"thanks doge\" in this channel.")

