#!/usr/bin/env python
# Shit kaboo says.avi
# by Corg-kun

from random import choice

quotes = [
"i make typos learn to live with it",
".go to order chicken from a place >p=lace is not open till 2 pm",
"if thats enough to confuse you then i sorry im so sorry",
"twhy is everyone treatig sugar lieks its cionyde?",
"life lesson: never sneeze into a fan",
"if your not going to make something the most comthing then you should not make anything",
"am i the onyl one that wants to punch a kitten eveytime some lama stuffer on 4chan says something anti jewish?",
"i know we should let micheal bay make an american doctor who movie and cast johnny depp as the doctor and megan fox as the compnaion and then we should mkae the tardis into a car",
"great now its playing barby girl FUCK THIS NOISE",
"how would a urinal eject steam?",
"who wants to sacrafice sasha grey to the eating monster?",
">anyone but me >good taste",
"why the hell is there on electroncs tools section anywhere THIS IS WHY I AHTE CARS!!!",
"giod dammit obama stop being whipped",
"whaty the drowning in period blood?",
"i would never advice someone to hit a baby for any reason",
"you did not lose gary i killed gary",
"there is no reason i should not be able to be pon secondlife for an entire month non stop",
"YAY IM A FATASS",
"if dovakin fus ro dahed and goku kamama waved who would win?",
"fuck prifacy you dont ghave that right",
"the amount i care about someone being sexist is so small you cuold fit it on a molocule",
"the wii has plenty of games",
"there is modern music on it so there is too much modern music i run too much of a risk of acciently listening to some",
"i sohlud never have to take responsibility fgor things i do people should takes steps to keep me from doing them",
"pokemon is a sexist show",
"linux isnt even important enough to be insulted ;-;",
"why is this guy slapping miku?",
"saying \"are you a trap or no\" is a mind trick to make someone think those are there only options and its just fucking annoying",
"there is something wrong with trying to stop me from lieing you you",
" im trying to put out the messagee that ugly people are weak and good looking people are strpong",
"i dont have boobs",
">tfw hungery",
"[me]feels the hot sauce hit its skin and panicks running aornd in a new world of pain searching desperatly for milk"
"O.O this game dont fuck around i already died ;-;",
"then whos dog did i eat?",
"its not allowed to be 4chans 9th birthday and moots an asshole for it",
"everything new is shit",
"and i would never in a million years pay ofr something like angry birds",
"zelda wind waker should be banned",
"when they get there set their truck on fire and rape them both brutally",
"i hate skateboards and i want to bash tony hawks skull in",
"im going to stab my fucking roomate with this screw driver",
"man fuck dogs",
"no WINDOWS>>>IS>>>BETTER>>>>FOR>>>GAMING *passes ou9t from hyper ventalating",
"god dammits mmos should exsist but i should never have to hear about them",
"god danm ponyfags",
"all films are bad period save for citizen cane",
"so a bunch of monkeys built a hunk of metal they can landpo n anothe planet?",
"focus stealing windows should be fucking illegal",
"that image is true though she is a stupuid fucking whore that cant take responsibility for her own actions",
"god dammit im going to kill someone at time warner WHY THE FUCK DOES DUNDAY NIGHT HAVE TO BE MAINTINENCE NIGHT??????",
"god fucking dammit i didnt do anything to anyone why the fuck is my net going so god danmed slow I DONT FUCKING DESERVE THIS SHIT",
"i should be allowed to go wponton murder on them for taking away the one thing that makes me happy",
"i would rather swallow  a goat leg whole",
"i would rather have a crocadile bite my legs off and live he rest of my life legless then play daikatana",
"if you dont chill im going to cme down there chain you up and sale you on the slave market",
"uhsed goods are responsible for bullshit li0ke gamestop its time for them to die",
">setting up things",
"god danmed morons and there stupidity",
">living",
]

print choice(quotes)
